## DEFAULT #####################################################################

[default]
#port        = "22"
#user        = "vuls"
#keyPath     = "/home/vuls/.ssh/id_rsa"

## DATABASES ###################################################################

[cveDict]
type = "sqlite3"
SQLite3Path = "/opt/vuls/cve-dictionary/cve.sqlite3"
#type = ["mysql", "postgres", "redis", "http" ]
#url = "https://cve.kaos.st"

[ovalDict]
type = "sqlite3"
SQLite3Path = "/opt/vuls/oval-dictionary/oval.sqlite3"
#type = ["mysql", "postgres", "redis", "http" ]
#url = "https://oval.kaos.st"

[gost]
type = "sqlite3"
SQLite3Path = "/opt/vuls/security-tracker/security-tracker.sqlite3"
#type = ["mysql", "postgres", "redis", "http" ]
#url = "https://gost.kaos.st"

[exploit]
type = "sqlite3"
SQLite3Path = "/opt/vuls/exploitdb/exploitdb.sqlite3"
#type = ["mysql", "postgres", "redis", "http" ]
#url = "https://exploitdb.kaos.st"

## SLACK #######################################################################

[slack]
#hookURL      = "https://hooks.slack.com/services/abc123/defghijklmnopqrstuvwxyz"
#legacyToken  = "xoxp-11111111111-222222222222-3333333333"
#channel      = "#channel-name"
#channel      = "${servername}"
#iconEmoji    = ":ghost:"
#authUser     = "username"
#notifyUsers  = ["@username"]

## EMAIL #######################################################################

[email]
#smtpAddr      = "smtp.gmail.com"
#smtpPort      = "587"
#user          = "username"
#password      = "password"
#from          = "from@address.com"
#to            = ["to@address.com"]
#cc            = ["cc@address.com"]
#subjectPrefix = "[vuls]"

## SYSLOG ######################################################################

[syslog]
#protocol    = "tcp"
#host        = "localhost"
#port        = "514"
#tag         = "vuls"
#facility    = "local0"
#severity    = "alert"
#verbose     = false
